### ISSUE TITLE
Modified DOSbox - where?

### ISSUE THREAD

**Issue by andrich48** [IllidanS4/pcsconv#1]
Where to download modified DOSBox version which creates pcs RPC output files?

**Comment by IS4Code** [comment]
Sorry, that would have been surely helpful to include this information in the readme file. My modified version of DOSBox can be found [here](https://www.vogons.org/viewtopic.php?p=325577&sid=20090296835840f86d0127adc41399c3#p325577) with all the instructions.
By the way, thanks for being the first one to comment here! If I may ask, what game/application are you going to record? If it is a soundtrack from a game, I would like to upload it to my channel on YouTube called SpeakerSoundtracks.

**Comment by andrich48** [comment]
Yeah I saw that link but I thought it is unstable or outdated.
Modified version was pre-compiled DOSBox for Windows binary, it also required additional "libgcc_s_dw2-1.dll" (had to download it manually).
That modified DOSBox has a bug: when launched under Windows XP x32, stderr or stdout channels are **not** redirected anywhere. When launched with "-noconsole" or "1>out.txt 2>&1" parameters in any combination, result is always same - empty files 'stderr.txt' and 'stdout.txt' are created **without any data**. 
"DOSBox Status Window" appears (when launched without parameters) and contains useful data but no way to get data in text file :(
Many old DOS games contain nice beep tunes, for example:
IBM Alley Cat (1984)
Accolade Grand Prix Circuit (1987)
Accolade The Cycles: International Grand Prix Racing (1989)
Microprose F-117A (1991)
I could not find any midi for them, so i'm looking for easy way to capture pc speaker sequences.

**Comment by IS4Code** [comment]
Unstable - yes (crashes on closing), outdated - there's nothing better. Sorry for the inconveniences, but I am no C++ programmer - I am glad that I found out what to edit and how to output it. I wonder, if you run normal stable DOSBox with the -noconsole parameter, does it output correctly the two files? Maybe it is an issue with the classic DOSBox on Windows XP, so someone could have already resolved it. If not, I could try to find out how to save data from these ports to a file.

Alley Cat and Grand Prix Circuit are already [here](http://speakersoundtracks.tk/soundtracks/) in usable formats. ☺ There also exists some conversion tool from DRO to MIDI.

**Comment by andrich48** [comment]
Sorry that was my fault about redirection problem :(( I was too impatient.
If anyone meets same problem, '-noconsole' switch for Modified DOSBox **works well**, but output is buffered. When any new data arrives, it is **not written immediately** to stdout.txt, but you should **wait for few seconds** before data is written.
Also, Modified DOSBoox crashes on closing but exits ok when you type 'exit' in DOS command line.
Thanks for collection of soundtracks, @IllidanS4!
It is nice but not complete ^_^
Grand Prix Circuit - "title" soundtrack is longer (can be fully recorded only from finish reward scene), "menu" soundtrack is also longer.
Alley Cat - only intro. There is also alley soundtrack (slower) and inside room soundtrack (faster) and final scene (when male cat meets female cat) ends with funny beep series.

**Comment by IS4Code** [comment]
Alright, thanks! I had little time to record all tunes from those games, so if you do it, please send me the txt/rpc files, thanks!
